/**
 * @file app_config.h
 * @brief Application-level configuration constants and task identifiers.
 */

#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#include "FreeRTOS.h"
#include "task.h"

/**
 * @brief Size of the COBS-encoded reception queue.
 */
#define ENCODED_QUEUE_SIZE 2048U

/**
 * @brief Size of the CDC transmit queue.
 */
#define CDC_TRANSMIT_QUEUE_SIZE 2048U

/**
 * @brief Data buffer size (used for inbound/outbound data).
 */
#define DATA_BUFFER_SIZE 20U

/**
 * @brief Size of the message header (ID + Command + Length).
 */
#define HEADER_SIZE 3U

/**
 * @brief Size of the checksum (1 byte).
 */
#define CHECKSUM_SIZE 1U

/**
 * @brief Maximum size of the COBS-encoded reception buffer.
 *
 * Calculation: input_length + (n/254) + Packet Marker.
 */
#define MAX_ENCODED_BUFFER_SIZE (DATA_BUFFER_SIZE + ((DATA_BUFFER_SIZE + 254U) / 254U) + 1U)

/**
 * @brief Data event queue size to store outbound data generated by inputs.
 */
#define DATA_EVENT_QUEUE_SIZE 500U

/**
 * @brief Marker indicating the end of a COBS packet.
 */
#define PACKET_MARKER (uint8_t)0x00

/**
 * @brief Panel ID for this device.
 */
#define BOARD_ID 0x01U

/**
 * @brief Task priorities.
 */
#define mainCDC_TASK_PRIORITY           (tskIDLE_PRIORITY + ( UBaseType_t ) 1U)
#define mainUART_TASK_PRIORITY          (tskIDLE_PRIORITY + ( UBaseType_t ) 1U)
#define mainLED_STATUS_TASK_PRIORITY    (tskIDLE_PRIORITY + ( UBaseType_t ) 1U)
#define mainDECODE_TASK_PRIORITY        (tskIDLE_PRIORITY + ( UBaseType_t ) 1U)
#define mainPROCESS_QUEUE_TASK_PRIORITY (tskIDLE_PRIORITY + ( UBaseType_t ) 1U)
#define mainADC_TASK_PRIORITY           (tskIDLE_PRIORITY + ( UBaseType_t ) 1U)
#define mainKEY_TASK_PRIORITY           (tskIDLE_PRIORITY + ( UBaseType_t ) 1U)
#define mainENCODER_TASK_PRIORITY       (tskIDLE_PRIORITY + ( UBaseType_t ) 1U)

/**
 * @brief FreeRTOS stack sizes for the tasks.
 */
#define CDC_STACK_SIZE              (3U * configMINIMAL_STACK_SIZE)
#define UART_EVENT_STACK_SIZE       (3U * configMINIMAL_STACK_SIZE)
#define LED_STATUS_STACK_SIZE       (2U * configMINIMAL_STACK_SIZE)
#define DECODE_RECEPTION_STACK_SIZE (3U * configMINIMAL_STACK_SIZE)
#define PROCESS_OUTBOUND_STACK_SIZE (3U * configMINIMAL_STACK_SIZE)
#define ADC_READ_STACK_SIZE         (4U * configMINIMAL_STACK_SIZE)
#define KEYPAD_STACK_SIZE           (5U * configMINIMAL_STACK_SIZE)
#define ENCODER_READ_STACK_SIZE     (5U * configMINIMAL_STACK_SIZE)

/**
 * @brief Task core affinity masks.
 */
#define CORE_0_AFFINITY (1U << 0U)
#define CORE_1_AFFINITY (1U << 1U)

/**
 * @brief Core affinity for the CDC task.
 */
#define CDC_TASK_CORE_AFFINITY              CORE_0_AFFINITY
#define UART_EVENT_TASK_CORE_AFFINITY       CORE_0_AFFINITY
#define LED_STATUS_TASK_CORE_AFFINITY       CORE_0_AFFINITY
#define DECODE_RECEPTION_TASK_CORE_AFFINITY CORE_1_AFFINITY
#define PROCESS_OUTBOUND_TASK_CORE_AFFINITY CORE_1_AFFINITY
#define ADC_READ_TASK_CORE_AFFINITY         CORE_1_AFFINITY
#define KEYPAD_TASK_CORE_AFFINITY           CORE_1_AFFINITY
#define ENCODER_READ_TASK_CORE_AFFINITY     CORE_1_AFFINITY

/**
 * @enum task_enum_t
 * @brief Enumerates the tasks created in the system.
 */
typedef enum task_enum_t {
	CDC_TASK,              /**< TinyUSB CDC device task */
	CDC_WRITE_TASK,        /**< USB CDC writer task */
	UART_EVENT_TASK,       /**< Task that reads bytes from TinyUSB */
	DECODE_RECEPTION_TASK, /**< Task that decodes inbound COBS packets */
	PROCESS_OUTBOUND_TASK, /**< Task that processes outbound events */
	ADC_READ_TASK,         /**< ADC reader task */
	KEYPAD_TASK,           /**< Keypad polling task */
	ENCODER_READ_TASK,     /**< Rotary encoder task */
	LED_STATUS_TASK,       /**< System status LED task */
	NUM_TASKS              /**< Number of tasks in the system */
} task_enum_t;

#endif // APP_CONFIG_H
