/**
 * @file app_config.h
 * @brief Application-level configuration constants and task identifiers.
 */

#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#include "FreeRTOS.h"
#include "task.h"

/**
 * @brief Size of the COBS-encoded reception queue, expressed in frames.
 *
 * Each queue slot holds a complete @ref encoded_frame_t produced by the
 * inbound framer, so the queue provides burst buffering equivalent to
 * @ref ENCODED_QUEUE_SIZE fully-assembled packets.
 */
#define ENCODED_QUEUE_SIZE 128U

/**
 * @brief Size of the CDC transmit queue.
 */
#define CDC_TRANSMIT_QUEUE_SIZE 2048U

/**
 * @brief Data buffer size (used for inbound/outbound data).
 */
#define DATA_BUFFER_SIZE 20U

/**
 * @brief Size of the message header (ID + Command + Length).
 */
#define HEADER_SIZE 3U

/**
 * @brief Size of the checksum (1 byte).
 */
#define CHECKSUM_SIZE 1U

/**
 * @brief Total unencoded message size (header + data + checksum).
 */
#define MESSAGE_SIZE (HEADER_SIZE + DATA_BUFFER_SIZE + CHECKSUM_SIZE)

/**
 * @brief Maximum size of the COBS-encoded reception buffer.
 *
 * Calculation: message_size + ceil(message_size/254) + Packet Marker.
 */
#define MAX_ENCODED_BUFFER_SIZE (MESSAGE_SIZE + ((MESSAGE_SIZE + 253U) / 254U) + 1U)

/**
 * @brief Chunk size used by @ref uart_event_task when draining the TinyUSB
 *        CDC RX FIFO.
 *
 * Sized generously above @ref MAX_ENCODED_BUFFER_SIZE so a single task loop
 * iteration can absorb a burst of several encoded frames, reducing the
 * number of @c tud_cdc_n_read / @c tud_cdc_n_available round-trips during
 * sustained high-throughput traffic.
 */
#define CDC_READ_CHUNK_SIZE 256U

/**
 * @brief Data event queue size to store outbound data generated by inputs.
 */
#define DATA_EVENT_QUEUE_SIZE 500U

/**
 * @brief Timeout for sending events to data queues (milliseconds).
 */
#define INPUT_QUEUE_SEND_TIMEOUT_MS 1000U

/**
 * @brief Retry delay for queue polling in task loops (milliseconds).
 */
#define QUEUE_RETRY_DELAY_MS 1U

/**
 * @brief Safety timeout used by @ref uart_event_task while blocked on a
 *        TinyUSB RX notification (milliseconds).
 *
 * The TinyUSB @c tud_cdc_rx_cb callback wakes the task as soon as bytes are
 * available.  This timeout provides a fallback so the task still services
 * the FIFO, updates its stack watermark and feeds the watchdog even if a
 * notification is ever missed.
 */
#define UART_EVENT_TASK_WAIT_MS 1000U

/**
 * @brief Safety timeout used by @ref cdc_task while blocked on the TinyUSB
 *        event queue (milliseconds).
 *
 * With @c CFG_TUSB_OS=OPT_OS_FREERTOS, @c tud_task_ext() sleeps on a kernel
 * queue and is woken by the USB IRQ.  The bounded wait ensures the task
 * still pets the watchdog and refreshes its stack watermark when no USB
 * activity is happening.
 */
#define CDC_TASK_SAFETY_TIMEOUT_MS 1000U

/**
 * @brief Marker indicating the end of a COBS packet.
 */
#define PACKET_MARKER (uint8_t)0x00

/**
 * @brief Panel ID for this device.
 */
#define BOARD_ID 0x01U

/**
 * @brief Task priorities.
 *
 * Communication tasks run one level above input scanning so that USB CDC
 * traffic is not preempted by keypad / ADC scans during bursts; the
 * difference is small enough that input scanning is not starved when
 * the bus is idle.
 */
#define mainCDC_TASK_PRIORITY           (tskIDLE_PRIORITY + ( UBaseType_t ) 2U)
#define mainUART_TASK_PRIORITY          (tskIDLE_PRIORITY + ( UBaseType_t ) 2U)
#define mainLED_STATUS_TASK_PRIORITY    (tskIDLE_PRIORITY + ( UBaseType_t ) 1U)
#define mainDECODE_TASK_PRIORITY        (tskIDLE_PRIORITY + ( UBaseType_t ) 2U)
#define mainPROCESS_QUEUE_TASK_PRIORITY (tskIDLE_PRIORITY + ( UBaseType_t ) 1U)
#define mainADC_TASK_PRIORITY           (tskIDLE_PRIORITY + ( UBaseType_t ) 1U)
#define mainKEY_TASK_PRIORITY           (tskIDLE_PRIORITY + ( UBaseType_t ) 1U)

/**
 * @brief FreeRTOS stack sizes for the tasks.
 */
#define CDC_STACK_SIZE              (3U * configMINIMAL_STACK_SIZE)
#define UART_EVENT_STACK_SIZE       (3U * configMINIMAL_STACK_SIZE)
#define LED_STATUS_STACK_SIZE       (2U * configMINIMAL_STACK_SIZE)
#define DECODE_RECEPTION_STACK_SIZE (3U * configMINIMAL_STACK_SIZE)
#define PROCESS_OUTBOUND_STACK_SIZE (3U * configMINIMAL_STACK_SIZE)
#define ADC_READ_STACK_SIZE         (4U * configMINIMAL_STACK_SIZE)
#define KEYPAD_STACK_SIZE           (5U * configMINIMAL_STACK_SIZE)

/**
 * @brief Task core affinity masks.
 */
#define CORE_0_AFFINITY (1U << 0U)
#define CORE_1_AFFINITY (1U << 1U)

/**
 * @brief Core affinity for the CDC task.
 */
#define CDC_TASK_CORE_AFFINITY              CORE_0_AFFINITY
#define UART_EVENT_TASK_CORE_AFFINITY       CORE_0_AFFINITY
#define LED_STATUS_TASK_CORE_AFFINITY       CORE_1_AFFINITY
#define DECODE_RECEPTION_TASK_CORE_AFFINITY CORE_1_AFFINITY
#define PROCESS_OUTBOUND_TASK_CORE_AFFINITY CORE_1_AFFINITY
#define ADC_READ_TASK_CORE_AFFINITY         CORE_1_AFFINITY
#define KEYPAD_TASK_CORE_AFFINITY           CORE_1_AFFINITY

/**
 * @enum task_enum_t
 * @brief Enumerates the tasks created in the system.
 */
typedef enum task_enum_t {
	CDC_TASK,              /**< TinyUSB CDC device task */
	CDC_WRITE_TASK,        /**< USB CDC writer task */
	UART_EVENT_TASK,       /**< Task that reads bytes from TinyUSB */
	DECODE_RECEPTION_TASK, /**< Task that decodes inbound COBS packets */
	PROCESS_OUTBOUND_TASK, /**< Task that processes outbound events */
	ADC_READ_TASK,         /**< ADC reader task */
	KEYPAD_TASK,           /**< Keypad polling + rotary encoder task */
	LED_STATUS_TASK,       /**< System status LED task */
	NUM_TASKS              /**< Number of tasks in the system */
} task_enum_t;

#endif // APP_CONFIG_H
