/**
 * @file app_context.h
 * @brief Shared application context (queues, task properties, line state).
 */

#ifndef APP_CONTEXT_H
#define APP_CONTEXT_H

#include <stdbool.h>

#include "FreeRTOS.h"
#include "queue.h"

#include "app_config.h"
#include "task_props.h"

/**
 * @struct app_context_t
 * @brief Holds shared resources required by multiple application domains.
 */
typedef struct app_context_t {
        QueueHandle_t encoded_reception_queue; /**< Queue storing encoded CDC bytes */
        QueueHandle_t data_event_queue;        /**< Queue with data events generated by inputs */
        QueueHandle_t cdc_transmit_queue;      /**< Queue with packets pending USB transmission */
        task_props_t task_props[NUM_TASKS];    /**< Task bookkeeping (handles, high watermark) */
        volatile bool cdc_rts;                 /**< USB CDC RTS flow control state */
        volatile bool cdc_dtr;                 /**< USB CDC DTR flow control state */
} app_context_t;

/**
 * @brief Retrieve the singleton application context.
 *
 * @return Pointer to the application context structure.
 */
app_context_t *app_context_get(void);

/**
 * @brief Reset task bookkeeping values to default (handle NULL, watermark 0).
 */
void app_context_reset_task_props(void);

/**
 * @brief Clear cached queue handles from the application context.
 */
void app_context_reset_queues(void);

/**
 * @brief Update cached CDC line state information.
 *
 * @param[in] dtr Data Terminal Ready state.
 * @param[in] rts Request To Send state.
 */
void app_context_set_line_state(bool dtr, bool rts);

/**
 * @brief Reset cached line state flags to `false`.
 */
void app_context_reset_line_state(void);

/**
 * @brief Check if the host is ready for USB CDC transfers.
 *
 * @return `true` when both DTR and RTS are asserted.
 */
static inline bool app_context_is_cdc_ready(void)
{
        const app_context_t *const context = app_context_get();
        return (context->cdc_dtr && context->cdc_rts);
}

/**
 * @brief Fetch task bookkeeping data for a given task identifier.
 *
 * @param[in] task_id Identifier of the requested task.
 * @return Pointer to the stored task properties.
 */
static inline task_props_t *app_context_task_props(task_enum_t task_id)
{
        return &app_context_get()->task_props[task_id];
}

/**
 * @brief Obtain the encoded reception queue handle.
 *
 * @return Queue handle or `NULL` if not initialised.
 */
static inline QueueHandle_t app_context_get_encoded_queue(void)
{
        return app_context_get()->encoded_reception_queue;
}

/**
 * @brief Update the encoded reception queue handle.
 *
 * @param[in] queue Queue handle to store.
 */
static inline void app_context_set_encoded_queue(QueueHandle_t queue)
{
        app_context_get()->encoded_reception_queue = queue;
}

/**
 * @brief Obtain the data event queue handle.
 *
 * @return Queue handle or `NULL` if not initialised.
 */
static inline QueueHandle_t app_context_get_data_event_queue(void)
{
        return app_context_get()->data_event_queue;
}

/**
 * @brief Store the data event queue handle.
 *
 * @param[in] queue Queue handle to store.
 */
static inline void app_context_set_data_event_queue(QueueHandle_t queue)
{
        app_context_get()->data_event_queue = queue;
}

/**
 * @brief Obtain the CDC transmit queue handle.
 *
 * @return Queue handle or `NULL` if not initialised.
 */
static inline QueueHandle_t app_context_get_cdc_transmit_queue(void)
{
        return app_context_get()->cdc_transmit_queue;
}

/**
 * @brief Store the CDC transmit queue handle.
 *
 * @param[in] queue Queue handle to store.
 */
static inline void app_context_set_cdc_transmit_queue(QueueHandle_t queue)
{
        app_context_get()->cdc_transmit_queue = queue;
}

#endif // APP_CONTEXT_H
