#ifndef COBS_H
#define COBS_H

#include <stddef.h>
#include <stdint.h>

/**
 * @file cobs.h
 * @brief Consistent Overhead Byte Stuffing (COBS) codec interface.
 */

/**
 * @brief Encode a payload using the COBS algorithm.
 *
 * The input buffer is transformed into a zero-free representation that is
 * suitable for framing protocols relying on a zero byte as packet delimiter.
 * The caller must ensure that @p buffer has enough space to hold the encoded
 * output (worst-case length equals input length plus one byte per 254 input
 * bytes).
 *
 * @param[in]  data    Pointer to the raw payload to encode.
 * @param[in]  length  Number of bytes in @p data.
 * @param[out] buffer  Destination buffer that receives the encoded bytes.
 *
 * @return Number of encoded bytes written to @p buffer.
 */
size_t cobs_encode(const void *data, size_t length, uint8_t *buffer);

/**
 * @brief Decode a COBS-encoded buffer.
 *
 * The function reconstructs the original payload generated by
 * cobs_encode(). Decoding stops when @p length bytes have been processed or
 * when a delimiter (code byte of zero) is encountered.
 *
 * @param[in]  buffer Pointer to the encoded input bytes.
 * @param[in]  length Number of encoded bytes available in @p buffer.
 * @param[out] data   Destination buffer receiving the decoded payload.
 *
 * @return Number of decoded payload bytes stored in @p data.
 */
size_t cobs_decode(const uint8_t *buffer, size_t length, void *data);

#endif /* COBS_H */
