#ifndef DATA_EVENT_H
#define DATA_EVENT_H

#include <stdint.h>

/**
 * @file data_event.h
 * @brief Data event representation exchanged with the host.
 */

/**
 * @brief Maximum payload size of a single data event.
 */
#define MAX_DATA_SIZE 10U

/**
 * @struct data_events_t
 * @brief Container for asynchronous payloads generated by input handlers.
 */
typedef struct data_events_t
{
        uint8_t command;                   /**< Command identifier to transmit. */
        uint8_t data_length;               /**< Number of valid bytes stored in @ref data. */
        uint8_t data[MAX_DATA_SIZE];       /**< Payload bytes associated with the command. */
} data_events_t;

#endif /* DATA_EVENT_H */
