# .github/workflows/build-dev-image.yml
name: Build Image & Push Embedded DevContainer Image

on:
  push:
    paths:
      - '.devcontainer/Dockerfile' 
      - '.devcontainer/**'         
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Build and Push Image Debian 12 ---
      - name: Define tags for Debian 12 image
        id: image_tags_debian12
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/devcontainer-embedded-debian
          echo "tag_latest=${IMAGE_NAME}:latest" >> $GITHUB_OUTPUT
          echo "tag_debian12=${IMAGE_NAME}:debian-12" >> $GITHUB_OUTPUT
          echo "tag_sha=${IMAGE_NAME}:${{ github.sha }}" >> $GITHUB_OUTPUT # Tag com o SHA do commit

      - name: Build and push Debian 12 DevContainer image
        uses: docker/build-push-action@v6
        with:
          context: .devcontainer 
          file: .devcontainer/Dockerfile 
          push: true
          tags: |
            ${{ steps.image_tags_debian12.outputs.tag_latest }}
            ${{ steps.image_tags_debian12.outputs.tag_debian12 }}
            ${{ steps.image_tags_debian12.outputs.tag_sha }}
          cache-from: type=gha 
          cache-to: type=gha,mode=max 
