name: "Build"

on:
  push:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup submodules"
        run: git submodule update --init --recursive
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: src
          build-dir: build
        